
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsurgtadygsjwlorudfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzdXJndGFkeWdzandsb3J1ZGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTE3NTAsImV4cCI6MjA2NjE2Nzc1MH0.r5heri_DJeicscCSsvd4HzsD_0LpQl7f47QpnDMUCgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
